version: "3.8"
services:
  react:
    build: .
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
  tests:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
    stdin_open: true
    tty: true
networks:
  default:
    name: react-nginx-network
