version: "3.8"
services:
  myalpine:
    env_file:
      - ./.env
    environment:
      - COMPOSE_PROJECT_NAME=myalpine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FOLDER=testFolder
    ports:
      - 80:80
      - 3030:4040
    volumes:
      - type: bind
        source: ./dataToMount
        target: /app/data
      - type: volume
        target: /app/anonymousData
      - type: volume
        source: db
        target: /app/data/mydb
volumes:
  db:
    external: true
