version: "3.8"
services:
  official_alpine:
    image: alpine
    command: ["ls"]
  myalpine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FOLDER=testFolder
    ports:
      - 80:80
      - 3030:4040
    volumes:
      - type: bind
        source: ./dataToMount
        target: /app/data
      - type: volumes
        target: /app/anonymousData
